name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.12
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
